### ISSUE TITLE
Filtrar nombre de profesores

### ISSUE THREAD

**Issue by DemianDrake** [gchaperon/uplanning#62]
Asegurarse que los nombres de profesores sean válidos (hasta con caracteres extranjeros, pero evitar símbolos que no corresponden).
![Screenshot_1](https://user-images.githubusercontent.com/22778283/67151815-94b42080-f2a1-11e9-8df4-99f2126121dd.jpg)

**Comment by gchaperon** [comment]
Esto creo que no es un bug, porque en vdd no le pasa nada a la base de datos si se ponen nombres raros. Pienso que la idea de esos nombres es cagarse el backend, pero si es seguro usarlos ya es problema del usuario que nombres de profe usa
