### ISSUE TITLE
Administrar sin iniciar sesión

### ISSUE THREAD

**Issue by DemianDrake** [gchaperon/uplanning#89]
Usando URLs para navegar, es posible acceder a partes del sitio que deberían ser accesibles sólo tras iniciar sesión como administrador. Por ahora no parece que las acciones tengan repercusiones, al no poseer permisos administrativos, pero de todas maneras es un potencial riesgo de seguridad.

![Screenshot_1](https://user-images.githubusercontent.com/22778283/69765062-3b1cfc80-1151-11ea-9748-e7da43996ab9.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/22778283/69765090-56880780-1151-11ea-8d7a-b800f84aa2f3.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/22778283/69765104-643d8d00-1151-11ea-80b1-c2c03fba088f.jpg)

**Comment by gchaperon** [comment]
esto esta bien, la unica informacion que se puede ver es la info publica de la api, es decir la misma del calendario, si te tratas de meter a la informacion de un curso especifico no se deberia poder ver.
la informacion publica no es necesario esconderla, esto no es un problema de seguridad
